name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip archive
        run: |
          mkdir -p extract
          unzip StakeWheel.zip -d extract/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_NORM }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=lasttest extract/

      - name: Setup Git Identity
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Cleanup Repository
        run: |
          # Удаляем все файлы и папки в корне, кроме .github и .git
          find . -maxdepth 1 ! -name '.github' ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} \;
          
          # Удаляем конкретный файл workflow
          rm -f .github/workflows/action.yml
          
          # Делаем коммит и пуш изменений
          git add -A
          git commit -m "Cleanup repository"
          git push https://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@github.com/BotTester321/main.git

