
name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # или ваша активная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_GLOBAL_APIKEY }}
          environment: 'production' # или ваше окружение

