
name: CI

on:
  push:
    branches:
      - main
      - staging
      - qa
  pull_request:

env:
  CF_ACCOUNT_ID: cd267cbd74046d020900533322f0fab8
  PAGES_PROJECT_NAME: newtest33
  CF_GLOBAL_APIKEY: 0914a4516cf998f05861259a99840e2d17e12
  CF_EMAIL: mailfortable@gmail.com
  SECRET_GIT: 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
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: '${{ env.CF_ACCOUNT_ID }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          api-key: '${{ env.CF_GLOBAL_APIKEY }}'
          email: '${{ env.CF_EMAIL }}'
          preview: true
          github-token: ${{ env.SECRET_GIT }}

      - name: Deploy qa/staging
        if: ${{ contains(fromJson('["refs/heads/qa", "refs/heads/staging"]'), github.ref) && github.event_name == 'push' }}
        uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: '${{ env.CF_ACCOUNT_ID }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          api-key: '${{ env.CF_GLOBAL_APIKEY }}'
          email: '${{ env.CF_EMAIL }}'
          branch: ${{ github.ref_name }}
          github-token: ${{ env.SECRET_GIT }}

      - name: Deploy production
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: '${{ env.CF_ACCOUNT_ID }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          api-key: '${{ env.CF_GLOBAL_APIKEY }}'
          email: '${{ env.CF_EMAIL }}'
          production: true
          github-token: ${{ env.SECRET_GIT }}
