
name: Deploy to environments

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: '${{ env.CF_ACCOUNT_ID }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          api-key: '${{ secrets.CF_GLOBAL_APIKEY }}'
          email: '${{ secrets.CF_EMAIL }}'
          branch: ${{ github.ref_name }}
          github-token: ${{ secrets.SECRET_GIT }}
        env:
          CF_ACCOUNT_ID: cd267cbd74046d020900533322f0fab8
          PAGES_PROJECT_NAME: rqrqrq
