name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Укажите версию Node.js, которая требуется для вашего проекта

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build # или ваша команда сборки

    - name: Deploy to Cloudflare Pages - Account 1
      if: github.ref == 'refs/heads/main'
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_NORM }}
        environment: 'production' # Адаптируйте среду, если это необходимо
