name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip archive
        run: |
          mkdir -p extract
          unzip StakeWheel.zip -d extract/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_NORM }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=lasttest extract/

      - name: Cleanup Repository
        run: |
          find . -maxdepth 1 ! -name '.github' ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} \;
          
          rm -f .github/workflows/action.yml
          
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Cleanup repository"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}


     


