
name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Или ваша ветка по умолчанию

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Добавьте шаги для сборки вашего сайта, если это необходимо
    # - name: Build
    #   run: команда_сборки

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.2UB4EV3HvqsJsK71yH7G0bwCI_pqewiZK3n8zr7V }}
        projectName: rqrqrq
        accountId: cd267cbd74046d020900533322f0fab8
