
name: CI

on:
  push:
    branches:
      - main
      - staging
      - qa
  pull_request:

env:
  CF_ACCOUNT_ID: your-cloudflare-account-id
  PAGES_PROJECT_NAME: your-pages-project-name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Добавьте шаги сборки вашего проекта здесь, если требуется
      # - name: Build
      #   run: ваша команда сборки

      - name: Deploy to Cloudflare Pages
        uses: tomjschuster/cloudflare-pages-deploy-action@v0.0.12
        with:
          account-id: ${{ env.CF_ACCOUNT_ID }}
          project-name: ${{ env.PAGES_PROJECT_NAME }}
          api-key: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          email: ${{ secrets.CF_EMAIL }}
          # Укажите 'true' для production или 'preview', или оставьте 'branch'
          production: true # Или 'preview' или 'branch: ${{ github.ref_name }}'
          github-token: ${{ secrets.SECRET_GIT }}
